In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('../market_data.db')

Rolling 20 day Average

In [15]:
query = """SELECT 
    date,
    ticker,
    close,
    AVG(close) OVER (
        PARTITION BY ticker 
        ORDER BY date 
        ROWS BETWEEN 19 PRECEDING AND CURRENT ROW
    ) AS rolling_avg
FROM prices
ORDER BY ticker, date
LIMIT 60
"""
df = pd.read_sql(query, conn)
df

          date ticker      close  rolling_avg
0   2021-03-26   ALHC  17.309999    17.309999
1   2021-03-29   ALHC  19.000000    18.155000
2   2021-03-30   ALHC  19.940001    18.750000
3   2021-03-31   ALHC  21.930000    19.545000
4   2021-04-01   ALHC  23.200001    20.276000
5   2021-04-05   ALHC  23.520000    20.816667
6   2021-04-06   ALHC  23.590000    21.212857
7   2021-04-07   ALHC  21.770000    21.282500
8   2021-04-08   ALHC  22.770000    21.447778
9   2021-04-09   ALHC  23.830000    21.686000
10  2021-04-12   ALHC  23.520000    21.852728
11  2021-04-13   ALHC  23.799999    22.015000
12  2021-04-14   ALHC  24.660000    22.218462
13  2021-04-15   ALHC  25.580000    22.458572
14  2021-04-16   ALHC  26.059999    22.698667
15  2021-04-19   ALHC  25.129999    22.850625
16  2021-04-20   ALHC  23.020000    22.860588
17  2021-04-21   ALHC  23.500000    22.896111
18  2021-04-22   ALHC  23.000000    22.901579
19  2021-04-23   ALHC  24.709999    22.992000
20  2021-04-26   ALHC  26.760000    23.464500
21  2021-04-27   ALHC  26.010000    23.815000
22  2021-04-28   ALHC  26.770000    24.156500
23  2021-04-29   ALHC  26.730000    24.396500
24  2021-04-30   ALHC  26.540001    24.563500
25  2021-05-03   ALHC  26.340000    24.704500
26  2021-05-04   ALHC  27.129999    24.881500
27  2021-05-05   ALHC  26.889999    25.137500
28  2021-05-06   ALHC  25.139999    25.256000
29  2021-05-07   ALHC  23.620001    25.245500
30  2021-05-10   ALHC  21.510000    25.145000
31  2021-05-11   ALHC  22.110001    25.060500
32  2021-05-12   ALHC  21.320000    24.893500
33  2021-05-13   ALHC  20.570000    24.643000
34  2021-05-14   ALHC  20.959999    24.388000
35  2021-05-17   ALHC  22.580000    24.260500
36  2021-05-18   ALHC  22.389999    24.229000
37  2021-05-19   ALHC  22.740000    24.191000
38  2021-05-20   ALHC  23.219999    24.202000
39  2021-05-21   ALHC  23.750000    24.154000
40  2021-05-24   ALHC  23.000000    23.966000
41  2021-05-25   ALHC  24.010000    23.866000
42  2021-05-26   ALHC  24.070000    23.731000
43  2021-05-27   ALHC  25.020000    23.645500
44  2021-05-28   ALHC  25.230000    23.580000
45  2021-06-01   ALHC  25.000000    23.513000
46  2021-06-02   ALHC  25.070000    23.410000
47  2021-06-03   ALHC  23.440001    23.237500
48  2021-06-04   ALHC  23.370001    23.149000
49  2021-06-07   ALHC  23.209999    23.128500
50  2021-06-08   ALHC  24.070000    23.256500
51  2021-06-09   ALHC  23.840000    23.343000
52  2021-06-10   ALHC  23.660000    23.460000
53  2021-06-11   ALHC  23.600000    23.611500
54  2021-06-14   ALHC  24.510000    23.789000
55  2021-06-15   ALHC  25.510000    23.935500
56  2021-06-16   ALHC  26.750000    24.153500
57  2021-06-17   ALHC  26.350000    24.334000
58  2021-06-18   ALHC  26.799999    24.513000
59  2021-06-21   ALHC  27.270000    24.689000

Daily returns + Rank

In [11]:
query = """
WITH returns AS (
    SELECT 
        date,
        ticker,
        close,
        (close - LAG(close) OVER (PARTITION BY ticker ORDER BY date)) 
            / LAG(close) OVER (PARTITION BY ticker ORDER BY date) AS daily_return
    FROM prices
)
SELECT 
    date,
    ticker,
    daily_return,
    RANK() OVER (PARTITION BY date ORDER BY daily_return DESC) AS return_rank
FROM returns
WHERE date = (SELECT MAX(date) FROM prices)
ORDER BY return_rank
"""
df = pd.read_sql(query, conn)
df

          date ticker  daily_return  return_rank
0   2026-09-25   ALHC      0.070404            1
1   2026-09-25   DDOG      0.043632            2
2   2026-09-25    JPM      0.013292            3
3   2026-09-25    NVS      0.013164            4
4   2026-09-25    KKR      0.010770            5
5   2026-09-25    AXP      0.010567            6
6   2026-09-25     BX      0.010323            7
7   2026-09-25    WFC      0.009613            8
8   2026-09-25   SNOW      0.005808            9
9   2026-09-25   BIIB      0.005478           10
10  2026-09-25    UNH      0.004213           11
11  2026-09-25   NVDA      0.002182           12
12  2026-09-25    AMD      0.002177           13
13  2026-09-25     MU      0.001620           14
14  2026-09-25    LLY      0.001328           15
15  2026-09-25      V     -0.001631           16
16  2026-09-25    MOH     -0.012674           17
17  2026-09-25    CRM     -0.017631           18